### ISSUE TITLE
H10 MOTD enhancement

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hs-puppet-environments#1]
the `h10-motd` is installed on all hackerspace computers, but currently there is only one motd.  Needs more! Come up with a motd list for day of the year?  or find an API we can pull from with a few of our own.

https://github.com/timberline-secondary/hackerspace-control-repo/blob/production/site/profile/files/config/h10-motd.sh

**Comment by punctuations** [comment]
Will do this using cowsay..

Still finding a good api

**Comment by punctuations** [comment]
I couldn't find a good API, instead, I have a manual list
